const en = {
  locale: "en",
  description: "Senior Data Engineer building dependable data foundations for better decisions.",
  nav: { about: "About", work: "Projects", experience: "Experience", contact: "Contact", language: "Language" },
  interface: { skipLink: "Skip to content", mainNavigation: "Main navigation", toggleNavigation: "Toggle navigation", aboutKicker: "01 / THE THREAD", workKicker: "02 / SELECTED WORK", skillsKicker: "03 / TOOLBOX", experienceKicker: "04 / CAREER", educationKicker: "05 / LEARNING", contactKicker: "06 / SAY HELLO", portraitTitle: "Carlos Dutra, Senior Data Engineer" },
  hero: {
    roleLine: "CARLOS DUTRA / SENIOR DATA ENGINEER",
    title: "I build the data foundation behind better decisions.",
    intro: "I trace numbers back to their definitions and systems, then build data people can use to decide.",
    note: "Curious by default. Particular about definitions.",
    workAction: "Explore selected work", contactAction: "Get in touch", portraitAlt: "Carlos Dutra smiling in his official profile portrait"
  },
  about: {
    title: "From business question to dependable data",
    body: "My path runs through RevOps, Data Analytics and Data Engineering. That mix taught me to ask what a number will help someone decide before choosing how to build the pipeline that produces it.",
    detail: "I work as a senior technical individual contributor: shaping architecture, building useful data products, and staying close to the business problem. A dashboard is only as trustworthy as the definitions and systems underneath it."
  },
  work: { title: "Selected work", intro: "Four projects where business questions shaped data products and engineering decisions.", openProject: "Explore project" },
  decisionLabels: { businessProblem: "Business problem", context: "Technical constraint", options: "Design alternatives", choice: "Decision", tradeoff: "Engineering trade-off", revisit: "Revisit when" },
  cases: [
    { id: "lumi", company: "MadeiraMadeira", project: "Lumi · People AI assistant", title: "An employee assistant grounded in People knowledge", summary: "Lumi helps employees find answers about People policies and processes through a conversational assistant.", contribution: "I designed and built the Python service, retrieving relevant knowledge passages and supplying them as context for Gemini responses.", technologies: ["Python", "RAG", "Google Chat", "Gemini"] },
    { id: "people-analytics", company: "MadeiraMadeira", project: "People Analytics · raw to Gold", title: "Building a People Analytics platform from source to Gold", summary: "I established the data foundation for a new People Analytics domain, evolving uncurated source data toward a Gold layer for analytical use.", contribution: "I designed the GCP foundations and delivery flow across BigQuery, Cloud Run, Cloud Composer, Dataform, and Terraform, separating source ingestion, conformance, and analytical modeling.", technologies: ["BigQuery", "Dataform", "Cloud Composer", "Cloud Run", "Terraform"] },
    { id: "hubspot-crm", company: "Gobrax", project: "HubSpot CRM modeling in BigQuery", title: "Turning CRM entities into analysis-ready models", summary: "HubSpot exposes flexible properties and linked objects; analytical use needs stable types, keys, relationships, and event grain.", contribution: "I built dbt models in BigQuery for companies, contacts, deals, and engagements: normalizing source properties, deduplicating mutable records, resolving CRM associations, and publishing curated deal and activity views.", technologies: ["BigQuery", "dbt", "SQL", "CRM data modeling"] },
    { id: "copapa-market-sizing", company: "COPAPA", project: "Market sizing · sales territory planning", title: "Estimating market potential to redesign sales territories", summary: "Commercial planning lacked a consistent view of category demand and market share across Brazilian municipalities.", contribution: "I combined IBGE demographics, ERP sales records, and industry data to model municipal demand and share estimates for a proposed territory redesign, keeping estimates distinct from realized sales.", technologies: ["Market modeling", "IBGE", "TOTVS Protheus", "Geospatial analysis"] }
  ],
  decisions: [
    { projectId: "lumi", company: "MadeiraMadeira", project: "Lumi · People AI assistant", businessProblem: "Employees needed timely, consistent answers to People policies without relying on a separate manual search for every question.", title: "Make retrieval an explicit input to generation", situation: "A language model's parametric knowledge does not identify which approved source supports an answer to a policy question.", options: "Provide policy text in a fixed prompt, or retrieve relevant passages from a maintained knowledge base for each question.", choice: "Retrieve ranked knowledge chunks from a vector index and pass them as context to the language model, keeping knowledge updates independent of model deployment.", tradeoff: "Retrieval adds components, and response quality remains bounded by corpus freshness, coverage, and ranking quality.", revisit: "Evaluation shows poor recall, stale sources, or recurring knowledge gaps." },
    { projectId: "people-analytics", company: "MadeiraMadeira", project: "People Analytics data platform", businessProblem: "People Analytics consumers needed responsive queries over growing facts while keeping operational cost and data freshness manageable.", title: "Materialize for access patterns; partition on event time", situation: "Repeated full scans of high-volume facts incur avoidable work, while dimensions have a different refresh and read pattern.", options: "Use views for every model, materialize every model arbitrarily, or choose storage by model role and query shape.", choice: "Materialize dimensions as tables and high-volume facts as tables partitioned by event date; cluster only on recurring filter or join keys.", tradeoff: "Materialization costs storage and rebuild work but lets recurring queries prune irrelevant partitions.", revisit: "Scan cost, freshness requirements, or consumer filter patterns change." },
    { projectId: "people-analytics", company: "MadeiraMadeira", project: "People Analytics data platform", businessProblem: "People Analytics needed dependable, reusable data products built from fragmented source systems, from raw records through business-ready Gold models.", title: "Separate source conformance from business semantics", situation: "Source schemas differ in types, naming, and history; mixing cleanup with business rules makes each consumer reimplement them.", options: "Expose source-shaped tables directly to BI, or separate source normalization from analytical modeling.", choice: "Use Bronze to retain source shape, Silver to cast, deduplicate, and normalize, and Gold to publish facts and dimensions in business terms.", tradeoff: "An extra transformation boundary increases model count but gives each model a narrower, testable responsibility.", revisit: "Source contracts change or a workload needs source-level detail." },
    { projectId: "hubspot-crm", company: "Gobrax", project: "HubSpot CRM modeling in BigQuery", businessProblem: "Commercial teams needed a consistent way to analyze HubSpot deals and engagements across linked, mutable CRM entities.", title: "Declare grain before joining entities", situation: "A CRM deal can link to multiple contacts, products, and activities; unrestricted joins can fan out rows and inflate measures.", options: "Aggregate source rows directly, or define each fact's grain and key and model many-to-many associations before aggregation.", choice: "I declare grain and business key per model, represent many-to-many relations through bridge models, and apply deterministic deduplication to mutable snapshots.", tradeoff: "More models and assertions upstream; less silent fan-out and clearer temporal semantics downstream.", revisit: "Source cardinality, business identity, or event lifecycle changes." }
  ],
  skills: { title: "Tools are useful. Judgment is the job.", summary: "Python · SQL · BigQuery · Google Cloud · Terraform · dbt · Dataform · RAG" },
  experience: { title: "A career close to the problem", items: [
    { org: "MadeiraMadeira", dates: "2026–present", role: "Data engineering", summary: "Building data products and platform capabilities in a large digital business." },
    { org: "Gobrax", dates: "2023–2026", role: "Data engineering", summary: "Worked across operational data, analytics engineering, and platform foundations in a logistics technology context." },
    { org: "Leads2b", dates: "2020–2022", role: "Customer Success analytics", summary: "Connected customer and commercial questions with analysis and operational insight." },
    { org: "COPAPA", dates: "2013–2018", role: "Commercial intelligence", summary: "Built an early foundation in automation, sales information, and practical business analysis." }
  ] },
  education: { title: "Education", items: [
    { name: "Computer Science", school: "Descomplica Faculdade Digital", dates: "2025–2028 · In progress" },
    { name: "Data Analytics · Lato Sensu postgraduate degree", school: "Descomplica Faculdade Digital", dates: "2021–2022 · Completed" },
    { name: "Business Administration", school: "UNOPAR", dates: "2015–2018 · Completed" }
  ] },
  contact: { title: "Have a good data problem?", intro: "I’m always interested in thoughtful engineering, useful data products, and conversations that start with a real question.", email: "Email", linkedin: "LinkedIn", github: "GitHub", whatsapp: "WhatsApp", footer: "Built with curiosity, a little healthy skepticism, and fewer spreadsheets than strictly necessary." }
};

en.pages = {
  home: { title: "Carlos Dutra · Senior Data Engineer", description: en.description },
  projects: { title: "Projects · Carlos Dutra", description: "Four selected data engineering and analytical projects by Carlos Dutra.", kicker: "SELECTED PROJECTS", heading: "Choose a problem. See how I approached it.", intro: "A short route to the work behind the headline. Each project has its own business context and technical decisions.", listLabel: "Selected projects" },
  project: { breadcrumbHome: "Home", breadcrumbProjects: "Projects", problem: "Business problem", contribution: "My contribution", approach: "Approach", status: "Result and status", technology: "Tools and methods", decisions: "Engineering decisions", back: "All projects", contact: "Start a conversation" }
};
en.projectDetails = {
  lumi: { problem: "Employees need a way to find answers about People policies and processes through a familiar conversational interface.", approach: "I built a Python service that retrieves relevant passages from maintained knowledge and supplies them as context for Gemini responses in Google Chat. The retrieval boundary makes the source of an answer a design concern rather than an implicit assumption.", status: "Built the retrieval-based Python service that grounds the employee assistant's answers in People knowledge." },
  "people-analytics": { problem: "A new People Analytics domain needed a dependable path from fragmented source records to reusable analytical models.", approach: "I shaped the GCP foundation and delivery flow across ingestion, source conformance, and analytical modeling. BigQuery, Cloud Run, Cloud Composer, Dataform, and Terraform have distinct responsibilities; Bronze, Silver, and Gold describe the conceptual data boundaries.", status: "Established platform foundations; the path from source systems toward Gold analytical models continues to evolve." },
  "hubspot-crm": { problem: "Commercial analysis needed consistent entities and measures despite flexible CRM properties, mutable records, and many-to-many associations.", approach: "I modeled companies, contacts, deals, and engagements with dbt and SQL in BigQuery. The work normalizes source properties, deduplicates mutable records, resolves associations, and declares grain before aggregating activities or deals.", status: "Published curated deal and activity views for consistent analysis across CRM entities." },
  "copapa-market-sizing": { problem: "Commercial planning needed a comparable estimate of demand and market share across Brazilian municipalities to inform sales territory design.", approach: "I combined IBGE demographics, ERP sales, and industry information at municipal level, built a repeatable estimate of potential demand, and compared estimates with observed sales. The distinction between modeled potential and realized sales stays explicit.", status: "Produced municipal planning estimates that informed a proposed territory redesign, with potential demand kept distinct from observed sales.", analysis: { title: "A comparable unit before a territory decision", body: "The analytical unit was the municipality. Aligning demographic, industry, and observed sales data at that level made locations comparable without treating a modeled estimate as a transaction. The method framed relative opportunity for a planning conversation while keeping projected demand separate from realized sales." } }
};

export default en;
