const ptBR = {
  locale: "pt-BR",
  description: "Engenheiro de Dados Sênior criando bases de dados confiáveis para decisões melhores.",
  nav: { about: "Sobre", work: "Projetos", experience: "Experiência", contact: "Contato", language: "Idioma" },
  interface: { skipLink: "Pular para o conteúdo", mainNavigation: "Navegação principal", toggleNavigation: "Alternar navegação", aboutKicker: "01 / A TRAJETÓRIA", workKicker: "02 / TRABALHOS SELECIONADOS", skillsKicker: "03 / FERRAMENTAS", experienceKicker: "04 / CARREIRA", educationKicker: "05 / FORMAÇÃO", contactKicker: "06 / VAMOS CONVERSAR", portraitTitle: "Carlos Dutra, Engenheiro de Dados Sênior" },
  hero: {
    roleLine: "CARLOS DUTRA / ENGENHEIRO DE DADOS SÊNIOR",
    title: "Construo a base de dados por trás de decisões melhores.",
    intro: "Investigo as definições e os sistemas por trás dos números, depois construo dados que as pessoas possam usar para decidir.",
    note: "Curioso por padrão. Cuidadoso com definições.",
    workAction: "Conheça alguns trabalhos", contactAction: "Entre em contato", portraitAlt: "Carlos Dutra sorrindo em seu retrato oficial de perfil"
  },
  about: {
    title: "Da pergunta de negócio a dados confiáveis",
    body: "Minha trajetória passa por RevOps, Análise de Dados e Engenharia de Dados. Essa combinação me ensinou a perguntar que decisão um número pode ajudar alguém a tomar antes de escolher como construir o pipeline que vai produzi-lo.",
    detail: "Atuo como especialista técnico sênior, com foco em contribuição técnica individual: desenho arquiteturas, construo produtos de dados úteis e mantenho proximidade com o problema de negócio. Um dashboard só é tão confiável quanto as definições e os sistemas que o sustentam."
  },
  work: { title: "Trabalhos selecionados", intro: "Quatro projetos em que perguntas de negócio orientaram produtos de dados e decisões de engenharia.", openProject: "Conheça o projeto" },
  decisionLabels: { context: "Restrição técnica", options: "Alternativas de desenho", choice: "Decisão", tradeoff: "Trade-off de engenharia", revisit: "Reavaliar quando" },
  cases: [
    { id: "lumi", company: "MadeiraMadeira", project: "Lumi · assistente de IA de People", summary: "O Lumi ajuda colaboradores a encontrar respostas sobre políticas e processos de People em uma interface conversacional.", contribution: "Projetei e desenvolvi o serviço em Python, recuperando trechos relevantes da base de conhecimento e fornecendo-os como contexto para as respostas do Gemini.", technologies: ["Python", "RAG", "Google Chat", "Gemini"] },
    { id: "people-analytics", company: "MadeiraMadeira", project: "People Analytics · do zero à Gold", summary: "Estruturei a base de dados de um novo domínio de People Analytics, evoluindo dados de origem ainda não curados em direção a uma camada Gold para análise.", contribution: "Desenhei as fundações em GCP e o fluxo de entrega com BigQuery, Cloud Run, Cloud Composer, Dataform e Terraform, separando ingestão, conformidade das fontes e modelagem analítica.", technologies: ["BigQuery", "Dataform", "Cloud Composer", "Cloud Run", "Terraform"] },
    { id: "hubspot-crm", company: "Gobrax", project: "Modelagem de CRM HubSpot em BigQuery", summary: "O HubSpot expõe propriedades flexíveis e objetos relacionados; a análise precisa de tipos, chaves, relações e grão de evento estáveis.", contribution: "Criei modelos dbt no BigQuery para empresas, contatos, negócios e interações: normalizei propriedades, dedupliquei registros mutáveis, resolvi associações do CRM e publiquei visões curadas de negócios e atividades.", technologies: ["BigQuery", "dbt", "SQL", "Modelagem de dados de CRM"] },
    { id: "copapa-market-sizing", company: "COPAPA", project: "Dimensionamento de mercado · planejamento territorial", summary: "O planejamento comercial não tinha uma visão consistente da demanda da categoria e da participação de mercado nos municípios brasileiros.", contribution: "Combinei dados demográficos do IBGE, vendas do ERP e informações setoriais para modelar demanda e participação estimadas por município para uma proposta de redesenho territorial, distinguindo estimativas de vendas realizadas.", technologies: ["Modelagem de mercado", "IBGE", "TOTVS Protheus", "Análise geográfica"] }
  ],
  decisions: [
    { projectId: "lumi", title: "Tratar recuperação como entrada explícita da geração", situation: "O conhecimento paramétrico do modelo, por si só, não identifica qual fonte aprovada sustenta uma resposta sobre uma política.", options: "Fornecer o texto da política em um prompt fixo ou recuperar trechos relevantes de uma base de conhecimento mantida para cada pergunta.", choice: "Recuperar trechos ranqueados de um índice vetorial e passá-los como contexto ao modelo, mantendo atualizações do conhecimento independentes do deploy do modelo.", tradeoff: "A recuperação acrescenta componentes, e a qualidade das respostas continua limitada pela atualização, cobertura e qualidade do ranking do corpus.", revisit: "Avaliações indicam baixa revocação, fontes desatualizadas ou lacunas recorrentes." },
    { projectId: "people-analytics", title: "Materializar conforme o acesso e particionar pelo tempo do evento", situation: "As áreas consumidoras precisavam de consultas rápidas com custo e atualização sob controle. Scans completos de fatos crescentes geram trabalho evitável; dimensões têm outros padrões de atualização e leitura.", options: "Usar views para todos os modelos, materializar tudo sem critério ou escolher armazenamento conforme papel e formato de consulta.", choice: "Materializar dimensões como tabelas e fatos volumosos como tabelas particionadas pela data do evento; clusterizar apenas por filtros ou chaves de junção recorrentes.", tradeoff: "Materialização consome armazenamento e exige rebuild, mas permite que consultas recorrentes descartem partições irrelevantes.", revisit: "Mudanças no custo de scan, nos requisitos de atualização ou nos padrões de filtro dos consumidores." },
    { projectId: "people-analytics", title: "Separar conformidade da fonte de semântica de negócio", situation: "Schemas de origem diferem em tipos, nomenclatura e histórico; misturar limpeza com regras de negócio faz cada consumidor reimplementá-las.", options: "Expor tabelas no formato da fonte diretamente para BI ou separar normalização de origem e modelagem analítica.", choice: "Usar Bronze para preservar a forma da origem, Silver para tipar, deduplicar e normalizar, e Gold para publicar fatos e dimensões em termos de negócio.", tradeoff: "Uma fronteira extra aumenta a quantidade de modelos, mas dá a cada um uma responsabilidade menor e testável.", revisit: "Mudanças nos contratos de origem ou uma análise que exija o detalhe original." },
    { projectId: "hubspot-crm", title: "Definir o grão antes de relacionar entidades", situation: "Um negócio de CRM pode se relacionar com vários contatos, produtos e atividades; joins sem restrição podem multiplicar linhas e inflar métricas.", options: "Agregar diretamente as linhas de origem ou declarar o grão e a chave de cada fato e modelar relações muitos-para-muitos antes da agregação.", choice: "Declaro grão e chave de negócio por modelo, represento relações muitos-para-muitos em modelos de associação e deduplico snapshots mutáveis com regra determinística.", tradeoff: "Mais modelos e assertions na origem; menos multiplicação silenciosa de linhas e semântica temporal mais clara no consumo.", revisit: "Mudanças na cardinalidade da fonte, na identidade de negócio ou no ciclo de vida dos eventos." }
  ],
  skills: { title: "Ferramentas ajudam. O trabalho é ter critério.", summary: "Python · SQL · BigQuery · Google Cloud · Terraform · dbt · Dataform · RAG" },
  experience: { title: "Uma carreira próxima do problema", items: [
    { org: "MadeiraMadeira", dates: "2026–atual", role: "Engenharia de dados", summary: "Construção de produtos de dados e capacidades de plataforma em um grande negócio digital." },
    { org: "Gobrax", dates: "2023–2026", role: "Engenharia de dados", summary: "Atuação com dados operacionais, engenharia analítica e fundamentos de plataforma em tecnologia para logística." },
    { org: "Leads2b", dates: "2020–2022", role: "Análise de Customer Success", summary: "Conexão entre perguntas de clientes e área comercial, análise e visão operacional." },
    { org: "COPAPA", dates: "2013–2018", role: "Inteligência comercial", summary: "Construção de uma base em automação, informação de vendas e análise prática de negócio." }
  ] },
  education: { title: "Formação", items: [
    { name: "Ciência da Computação", school: "Descomplica Faculdade Digital", dates: "2025–2028 · Em andamento" },
    { name: "Pós-graduação Lato Sensu em Data Analytics", school: "Descomplica Faculdade Digital", dates: "2021–2022 · Concluída" },
    { name: "Administração", school: "UNOPAR", dates: "2015–2018 · Concluída" }
  ] },
  contact: { title: "Tem um bom problema de dados?", intro: "Gosto de engenharia bem pensada, produtos de dados úteis e conversas que começam com uma pergunta real.", email: "E-mail", linkedin: "LinkedIn", github: "GitHub", whatsapp: "WhatsApp", footer: "Feito com curiosidade, uma dose saudável de ceticismo e menos planilhas do que seria estritamente necessário." }
};

ptBR.pages = {
  home: { title: "Carlos Dutra · Engenheiro de Dados Sênior", description: ptBR.description },
  projects: { title: "Projetos · Carlos Dutra", description: "Quatro projetos selecionados de engenharia e análise de dados de Carlos Dutra.", kicker: "PROJETOS SELECIONADOS", heading: "Escolha um problema. Veja como eu o abordei.", intro: "Um caminho curto até o trabalho por trás da apresentação. Cada projeto tem seu contexto de negócio e suas decisões técnicas.", listLabel: "Projetos selecionados" },
  project: { breadcrumbHome: "Início", breadcrumbProjects: "Projetos", problem: "Problema de negócio", contribution: "Minha contribuição", technology: "Ferramentas e métodos", decisions: "Decisões de engenharia", back: "Todos os projetos", contact: "Vamos conversar" }
};
ptBR.projectDetails = {
  lumi: { problem: "Colaboradores precisam de respostas consistentes e atualizadas sobre políticas e processos de People no Google Chat.", contribution: "Projetei e desenvolvi o serviço do assistente, conectando as perguntas dos colaboradores à base de conhecimento de People." },
  "people-analytics": { problem: "Um novo domínio de People Analytics precisava de um caminho confiável entre registros de fontes fragmentadas e modelos analíticos reutilizáveis.", contribution: "Desenhei as fundações na nuvem e o fluxo de entrega, separando ingestão, conformidade das fontes e modelagem analítica. O caminho até os modelos Gold continua evoluindo." },
  "hubspot-crm": { problem: "A análise comercial precisava de entidades e medidas consistentes apesar de propriedades flexíveis do CRM, registros mutáveis e associações muitos-para-muitos.", contribution: "Criei modelos de empresas, contatos, negócios e interações: normalizei propriedades, dedupliquei registros e resolvi associações do CRM. Publiquei visões curadas de negócios e atividades para análise." },
  "copapa-market-sizing": { problem: "O planejamento comercial não tinha uma visão consistente da demanda da categoria e da participação de mercado nos municípios brasileiros.", contribution: "Combinei dados demográficos, setoriais e vendas do ERP para estimar demanda e participação de mercado por município. Essas estimativas orientaram uma proposta de redesenho dos territórios de vendas.", analysis: { title: "Uma unidade comparável antes da decisão territorial", body: "O município foi a unidade de análise, permitindo comparar localidades. A comparação entre potencial modelado e vendas observadas contextualizou a oportunidade relativa para o planejamento; as estimativas foram mantidas distintas das vendas realizadas." } }
};

export default ptBR;
